# -*- coding: utf-8 -*-
"""EliteMobs のダンジョン名/モブ名の日本語訳表。

gen-mob-overrides.py と gen-em-manifest.py の両方から読む単一の正本。
キーは EliteMobs 側の英語表記(色コード除去済み)。ここに無い名前は英語のまま残す。
"""

# ワールド名(設計図名) -> 日本語のダンジョン名
DUNGEON_JA = {
    "em_adventurers_guild": "冒険者ギルド(拠点)",
    "em_beasts_sanctuary": "獣の聖域",
    "em_id_binder_of_worlds": "世界を繋ぐ者の聖所",
    "em_id_bone_monastery": "骨の修道院",
    "em_the_catacombs": "カタコンベ",
    "em_id_craftenmines_lab": "クラフテンマイン研究所",
    "em_the_dark_cathedral": "闇の大聖堂",
    "em_diamond_arena": "ダイヤモンドリーグ闘技場",
    "em_fireworks": "花火工房",
    "em_id_frost_palace": "氷結宮殿",
    "em_hallosseum": "ハロウィン闘技場",
    "em_invasion": "侵攻ミニダンジョン",
    "em_iron_league_arena": "アイアンリーグ闘技場",
    "em_knight_castle": "騎士団の城",
    "em_north_pole": "北極ミニダンジョン",
    "em_oasis": "オアシス",
    "em_id_oasis_pyramid": "オアシスのピラミッド",
    "em_the_pirate_ship": "海賊船",
    "em_primis": "プリミス",
    "em_id_bloodtemple": "プリミス 血の神殿",
    "em_id_primis_gladius": "プリミス グラディウス侵攻",
    "em_sewer_maze": "下水道迷宮",
    "em_steamworks_lair": "蒸気機関工房",
    "em_the_airship": "飛空艇",
    "em_id_the_bridge": "古橋の聖所",
    "em_id_the_cave": "灼熱の洞窟",
    "em_id_the_city": "ドワーフの地下都市",
    "em_id_the_climb": "登攀路",
    "em_the_colosseum": "コロシアム",
    "em_dark_spire": "暗黒の尖塔",
    "em_id_the_deep_mines": "深層鉱山",
    "em_id_the_hallowed_haunt": "聖域の怪異",
    "em_id_the_mines": "鉱山",
    "em_id_the_nether_bell": "ネザーの鐘",
    "em_id_the_nether_wastes": "ネザーの荒野",
    "em_id_the_palace": "宮殿",
    "em_id_the_quarry": "採石場",
    "em_the_ruins": "遺跡",
    "em_under_grove": "地下樹林",
    "em_the_vampire_manor": "吸血鬼の館",
    "em_yggdrasil": "ユグドラシル",
}
for _n in range(1, 21):
    DUNGEON_JA[f"em_id_enchantment_challenge_{_n}"] = f"エンチャント試練 {_n}"

# EliteMobs のモブ表示名(英語) -> 日本語
MOB_JA = {
    "1337 Summ0n3r": "1337 サモナー",
    "Abyssal Follower of Cthulhu": "深淵のクトゥルフ信徒",
    "Agdluak": "アグドルアク",
    "Ancient Bones": "古代の骨",
    "Ancient Corpse": "古代の死骸",
    "Ancient Crawler": "古代の這うもの",
    "Ancient Dwarf": "古代のドワーフ",
    "Ancient Guardian": "古代の守護者",
    "Ancient Husk": "古代のハスク",
    "Arachnidian Construct": "蜘蛛型構造体",
    "Arcane Knight": "秘術の騎士",
    "Archery Club Enthusiast": "弓術部員",
    "Arena Archer": "闘技場の射手",
    "Arena Crossbowman": "闘技場のクロスボウ兵",
    "Arena Healer": "闘技場の治癒師",
    "Arena Swordsman": "闘技場の剣士",
    "Arena Zombie": "闘技場のゾンビ",
    "Arrow Dispenser": "矢の射出装置",
    "Arrow Launcher": "矢の発射機",
    "Azaroon Healer": "アザルーンの治癒師",
    "Bad Doggo": "悪い犬",
    "Bad Pupper": "悪い子犬",
    "Binder of Worlds": "世界を繋ぐ者",
    "Black Philip": "黒山羊フィリップ",
    "Bleached Bones": "白化した骨",
    "Boiled Bones": "煮られた骨",
    "Boomi": "ブーミ",
    "Bow Dispenser": "弓の射出装置",
    "Brave Knight": "勇敢な騎士",
    "Broiled Miner": "焼かれた坑夫",
    "Broiled Villager": "焼かれた村人",
    "CLK-WRx702": "CLK-WRx702",
    "Calcium Miner": "石灰の坑夫",
    "Captured Villager": "囚われの村人",
    "Charlemagne": "シャルルマーニュ",
    "Charred Villager": "炭化した村人",
    "Child of Cthulhu": "クトゥルフの落とし子",
    "City Defender": "都市の防衛兵",
    "City Guard": "都市の衛兵",
    "City Watcher": "都市の監視者",
    "Corrupted Blacksmith": "堕落した鍛冶師",
    "Corrupted Digger": "堕落した掘削者",
    "Cowardly Knight": "臆病な騎士",
    "Crawler": "這うもの",
    "Crucio the Bearer of Curses": "呪いを運ぶ者クルーシオ",
    "Crusty Bones": "干からびた骨",
    "Cultist of Cthulhu": "クトゥルフの狂信者",
    "Daredevil": "命知らず",
    "Dark Flame": "暗黒の炎",
    "Deadly Miasma": "致死の瘴気",
    "Dedicated Miner": "熱心な坑夫",
    "Disturbed Bones": "荒らされた骨",
    "Disturbed Carcass": "荒らされた亡骸",
    "Doomball": "破滅の球",
    "Dried Corpse": "干からびた死骸",
    "Drone L-2": "ドローン L-2",
    "Drone R-1": "ドローン R-1",
    "Drowned King": "溺死者の王",
    "Drowned One": "溺死せし者",
    "Dullahan": "デュラハン",
    "Dummy Surprise": "サプライズダミー",
    "Dwarven Corpse": "ドワーフの死骸",
    "Dwarven Deathknight": "ドワーフの死の騎士",
    "Dwarven Miner": "ドワーフの坑夫",
    "Dwarven Warrior": "ドワーフの戦士",
    "Dwarven Worker": "ドワーフの労働者",
    "Eidolon": "幻影エイドロン",
    "Encased Miner": "閉じ込められた坑夫",
    "Energized Bunny": "帯電したウサギ",
    "Exhausted Prospector": "疲弊した探鉱者",
    "Fallen Gardener": "堕ちた庭師",
    "Fencing Club Enthusiast": "フェンシング部員",
    "Fireball": "火の玉",
    "Flame": "焔",
    "Focused Thought": "凝集した思念",
    "Follower of Cthulhu": "クトゥルフの信徒",
    "Forgotten Hero": "忘れられた英雄",
    "Forgotten Miner": "忘れられた坑夫",
    "Former Defender": "かつての防衛兵",
    "Fossilized Bones": "化石化した骨",
    "Fractured Essence": "砕けた精髄",
    "Frostball": "氷の玉",
    "Gel Head Villager": "ゲル頭の村人",
    "Gnasuran Electrohead": "グナスラの電気頭",
    "Gnasuran Machinist": "グナスラの機械技師",
    "Gnasuran Tinkerer": "グナスラの修理屋",
    "Greedy Miner": "強欲な坑夫",
    "Heavy Miasma": "重い瘴気",
    "Hellstar": "地獄星",
    "Hexer": "呪術師",
    "Holder of Light": "光を抱く者",
    "Holder of Misery": "悲嘆を抱く者",
    "Holder of Void": "虚無を抱く者",
    "Hollow Dwarf": "空虚なドワーフ",
    "Ice Wraith": "氷の亡霊",
    "Infused Soul": "注ぎ込まれた魂",
    "Jack Frost": "ジャックフロスト",
    "Jealous Block": "嫉妬するブロック",
    "Jeffrey": "ジェフリー",
    "Krampus": "クランプス",
    "Lesser Nether Fiend": "下級ネザーの魔物",
    "Lesser Swarmling": "下級の群体",
    "Lift Air Filler": "昇降機の送気装置",
    "Lift Master": "昇降機の管理者",
    "Lift State Zero": "昇降機 状態ゼロ",
    "Living Slime": "生きたスライム",
    "Lost Dwarf": "迷えるドワーフ",
    "Lost Wanderer": "迷える放浪者",
    "Loveable Impaler": "愛らしき串刺し公",
    "Loyal Steed": "忠実な軍馬",
    "Lurker": "潜むもの",
    "Mad Dwarf": "狂ったドワーフ",
    "Magicked Creeper": "魔力を帯びたクリーパー",
    "Mirage": "蜃気楼",
    "Mjolnir": "ミョルニル",
    "Molten Marvel": "溶融の驚異",
    "Monster Corpse": "怪物の死骸",
    "Mr. Oinkers": "ブヒ氏",
    "Mr. Oinkers Fan": "ブヒ氏のファン",
    "Mrs. Claus": "クロース夫人",
    "Nether Beast": "ネザーの獣",
    "Nether Deviling": "ネザーの小悪魔",
    "Nether Feeder": "ネザーの捕食者",
    "Nether Fiend": "ネザーの魔物",
    "Nether Moss": "ネザーの苔",
    "Nether Moss # SKIN ME WHEN mineskins is back up!": "ネザーの苔",
    "Nether Shroom": "ネザーのキノコ",
    "Nether Sporeflinger": "ネザーの胞子飛ばし",
    "Nether Sprite": "ネザーの精霊",
    "Obsidian Hound": "黒曜石の猟犬",
    "Old Stone King": "古き石の王",
    "Ore Hauler": "鉱石運搬者",
    "Ore Transporter": "鉱石輸送機",
    "Partygoer": "パーティー客",
    "Piranha King": "ピラニアの王",
    "Piranha Prince": "ピラニアの王子",
    "Quarry Guard": "採石場の番人",
    "Ravegarer": "レイヴ荒らし",
    "Reality Corruptor": "現実を汚す者",
    "Reality Harbinger": "現実の先触れ",
    "Reality Riftrender": "現実を裂く者",
    "Reality Ruiner": "現実を滅ぼす者",
    "Reality Rupturer": "現実を破る者",
    "Reality Shredder": "現実を切り刻む者",
    "Reality Slayer": "現実を屠る者",
    "Reality Uprooter": "現実を根こそぎにする者",
    "Reality Waster": "現実を荒らす者",
    "Reality Wrencher": "現実をねじる者",
    "Reanimated Resident": "蘇った住人",
    "Rearranged Flesh": "組み替えられた肉",
    "Reinforced Frame": "強化された骨組み",
    "Rejected Mass": "拒絶された肉塊",
    "Resurrected Beast": "蘇生した獣",
    "Rock Solid Cold": "岩のような極寒",
    "Rotting Carcass": "腐りゆく亡骸",
    "Royal Archer": "王室の射手",
    "Royal Guard": "王室の近衛",
    "Royal Spellcaller": "王室の招霊術士",
    "Royal Spellcaster": "王室の術士",
    "Royal Spellinvoker": "王室の詠唱術士",
    "Royal Spellslinger": "王室の速射術士",
    "Royal Spellweaver": "王室の織成術士",
    "Santa Claus": "サンタクロース",
    "Santa's Elf": "サンタのエルフ",
    "Seasoned Miner": "熟練の坑夫",
    "Ser Prancelot": "跳ねるランスロット卿",
    "Sewer Beast": "下水道の獣",
    "Sewer Monstrosity": "下水道の異形",
    "Sewer Piranha": "下水道のピラニア",
    "Sewer worker": "下水道の作業員",
    "Shadow": "影",
    "Shadow Archer": "影の射手",
    "Shambling Dwarf": "よろめくドワーフ",
    "Shifting Miner": "揺らめく坑夫",
    "Slow Giver": "鈍化を与える者",
    "Smuggler": "密輸業者",
    "Snowy Wraith": "雪の亡霊",
    "Soul Mass": "魂の塊",
    "Soul Shadow": "魂の影",
    "Soul Splintering": "魂の裂片",
    "Soul Tulpa": "魂のトゥルパ",
    "Soul of Endurance": "忍耐の魂",
    "Soul of Haste": "俊敏の魂",
    "Soul of Undying": "不滅の魂",
    "Soul of the Naughty List": "お仕置きリストの魂",
    "Soulweaver Daine": "魂織りのデイン",
    "Spark": "火花",
    "Sparky": "スパーキー",
    "Spellkeeper Totem": "術式守護のトーテム",
    "Spiderling": "小蜘蛛",
    "Spirit Whisperer": "霊と囁く者",
    "Spooky Skeleton": "不気味なスケルトン",
    "Stone Guardian": "石の守護者",
    "Strange TNT": "奇妙なTNT",
    "Swarmling": "群体",
    "TNT": "TNT",
    "The Boiler": "煮沸炉",
    "The Firebunger": "火炎装置",
    "The Foreman": "現場監督",
    "The Glass Master": "硝子の達人",
    "The Grill Master": "焼き場の達人",
    "The Jester": "道化師",
    "The Obsidian Shroud": "黒曜石の帳",
    "The Shadowmaster": "影の支配者",
    "The Southern Viper": "南方の毒蛇",
    "The Thunder Smith": "雷の鍛冶師",
    "The Void Bell": "虚無の鐘",
    "Thick Miasma": "濃い瘴気",
    "Thousand Blades": "千の刃",
    "Toxic Gardener": "有毒の庭師",
    "Toxic Miasma": "有毒の瘴気",
    "Transmuted Flesh": "変成した肉",
    "Tricky Bones": "厄介な骨",
    "Trident Launcher": "トライデント発射機",
    "Twisted Excavator": "捻じれた掘削機",
    "Twisted Miner": "捻じれた坑夫",
    "Undead": "アンデッド",
    "Undead Beast": "アンデッドの獣",
    "Undead Beastmaster": "アンデッドの調獣師",
    "Undead Bruiser": "アンデッドの荒くれ",
    "Undead Rat": "アンデッドのネズミ",
    "Undead Villager": "アンデッドの村人",
    "Unrotten": "腐らざる者",
    "Uther Stan": "ウーサー・スタン",
    "Uther the Champion": "覇者ウーサー",
    "Village Champion": "村の勇者",
    "Village Guardian": "村の守護者",
    "Void Piercer": "虚無を貫く者",
    "Void Shrike": "虚無のモズ",
    "Void Walker": "虚無を歩む者",
    "Weak Swarmling": "脆弱な群体",
    "Weird Cow": "奇妙な牛",
    "Withered Corpse": "萎びた死骸",
    "Workshop Elf": "工房のエルフ",
    "Worshipper of Cthulhu": "クトゥルフの崇拝者",
    "Zoltan": "ゾルタン",
    "a": "電撃の増援",  # 原文が &k(難読化コード)のみで読めないモブ
    "[Lv.1 Training Dummy]": "訓練用ダミー Lv.1",
    "[Lv.25 Training Dummy]": "訓練用ダミー Lv.25",
    "[Lv.50 Training Dummy]": "訓練用ダミー Lv.50",
    "[Lv.75 Training Dummy]": "訓練用ダミー Lv.75",
    "[Lv.100 Training Dummy]": "訓練用ダミー Lv.100",
}

# モブidの接尾辞 -> 日本語の役割サフィックス。同名の別個体(フェーズ/召喚体)を
# 表示名だけで見分けられるようにする。
SUFFIX_JA = [
    ("_phase_0", " (第1段階)"),
    ("_phase_1", " (第2段階)"),
    ("_phase_2", " (第3段階)"),
    ("_phase_3", " (第4段階)"),
    ("_p1", " (第1段階)"),
    ("_p2", " (第2段階)"),
    ("_p3", " (第3段階)"),
    ("_p4", " (第4段階)"),
    ("_p5", " (第5段階)"),
    ("_p6", " (第6段階)"),
    ("_p7", " (第7段階)"),
    ("_reinforcement", " (増援)"),
    ("_summon", " (召喚体)"),
    ("_mount", " (騎乗体)"),
    ("_drone", " (随伴機)"),
    ("_corpse", " (亡骸)"),
    ("_normal", " (通常)"),
    ("_hard", " (上級)"),
    ("_mythic", " (神話)"),
]


# 同一ダンジョン内で表示名が衝突したときの、モブid別の追加識別子。
# 一般則(第N波 / 第N段階)で割れないものだけをここに明示する。
DISAMBIGUATION_JA = {
    "the_climb_undead_beastmaster": " (本体)",
    "em_id_the_nether_bell_beam_boss_green_1_speed": " (俊敏)",
    "em_id_the_nether_bell_beam_boss_green_2_strength": " (剛力)",
    "em_id_the_nether_bell_beam_boss_green_3_night_vision": " (暗視)",
    "em_id_the_nether_bell_beam_boss_red_1_slow": " (鈍足)",
    "em_id_the_nether_bell_beam_boss_red_2_hunger": " (飢餓)",
    "em_id_the_nether_bell_beam_boss_red_3_darkness": " (暗闇)",
    "em_id_the_nether_bell_beam_boss_yellow_1_bogged": " (沼)",
    "em_id_the_nether_bell_beam_boss_yellow_2_breeze": " (ブリーズ)",
    "em_id_the_nether_bell_beam_boss_yellow_3_warden": " (ウォーデン)",
    "em_id_the_nether_bell_beam_boss_yellow_3_warden_power_dummy": " (ウォーデン・出力ダミー)",
    "em_id_the_nether_bell_beam_boss_yellow_1_bogged_summon": " (沼)",
    "em_id_the_nether_bell_beam_boss_yellow_2_breeze_summon": " (ブリーズ)",
    "em_id_the_nether_bell_beam_boss_yellow_3_warden_summon": " (ウォーデン)",
    "em_id_the_nether_bell_world_disturbed_melee": " (近接)",
    "em_id_the_nether_bell_world_disturbed_waker": " (覚醒役)",
    "the_palace_old_stone_king_summon_1": " (1体目)",
    "the_palace_old_stone_king_summon_2": " (2体目)",
    "LiftStateOne": " (段階1)",
    "LiftStateTwo": " (段階2)",
    "LiftStateThree": " (段階3)",
    "LiftStateFour": " (段階4)",
    "LiftStateFinishDungeon": " (最終段階)",
    "em_id_the_quarry_lift_creeper": " (本体)",
    "em_id_the_quarry_lift_creeper_activator": " (起動役)",
    "em_id_the_quarry_lift_creeper_wizard_spawner": " (術者スポナー)",
    "em_id_the_quarry_quarry_guard": " (成体)",
    "em_id_the_quarry_quarry_guard_baby": " (幼体)",
    "enchantment_boss_leet_summoner_eidolon_one": " (1体目)",
    "enchantment_boss_leet_summoner_eidolon_two": " (2体目)",
    "dark_cathedral_tier_75_area_folk": " (エリア)",
    "dark_cathedral_tier_75_surprise_folk": " (奇襲)",
    "the_steamworks_gnasuran_tinkerer": " (本体)",
    "the_steamworks_gnasuran_weather_activate": " (天候起動役)",
    "wood_league_wave_16_melee": " (近接)",
    "wood_league_wave_16_ranged": " (遠隔)",
}
