package com.trinityforge.config.domains;

import com.trinityforge.config.LoadableConfig;
import com.trinityforge.mobs.ConversionPolicy.Ramp;
import com.trinityforge.mobs.MobIdNormalizer;
import com.trinityforge.mobs.MobOverrideDropEntry;
import com.trinityforge.mobs.MobOverrideEntry;
import com.trinityforge.mobs.MobProfile;
import com.trinityforge.mobs.MobStatOverride;
import com.trinityforge.mobs.RampParser;
import org.bukkit.Material;
import org.bukkit.configuration.ConfigurationSection;
import org.bukkit.configuration.InvalidConfigurationException;
import org.bukkit.configuration.file.YamlConfiguration;
import org.bukkit.plugin.Plugin;

import java.io.File;
import java.io.IOException;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Optional;
import java.util.OptionalInt;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * Loader for {@code combat/mob-overrides.yml} (2026-07-26 「エリートモブズインスタンス内のカスタムモブ
 * ごとに個別のドロップテーブルと強さテーブルを設定できる」要望): a "ダンジョン(ワールド) × モブid" overlay
 * layered ON TOP of the autogenerated {@code combat/mob-profiles.yml} (never edited by this feature —
 * {@code /trinityforge importmobs} owns that file and would wipe hand edits on re-import).
 *
 * <p><b>Structure</b>: {@code overrides.<worldName>.mobs.<mobId>} for a world-specific entry, or
 * {@code overrides.default.mobs.<mobId>} for the全ダンジョン共通フォールバック. The world key may be either
 * the live world name or an instanced dungeon's blueprint world name, which then covers every instance
 * of that dungeon — see {@link #worldScopeKey}. {@code overrides:} absent or empty is a LOGICAL no-op
 * ({@link #resolve} always returns {@code base} unchanged and {@link #dropsFor}/{@link #vanillaExpFor}
 * always return empty) — but that is a code guarantee, not a description of the shipped resource file.
 * <b>The shipped {@code combat/mob-overrides.yml} is NOT empty</b>: as of 2026-07-26 it ships with
 * {@code overrides:} already populated for 396 dungeon mobs, and {@link #load} (via
 * {@code plugin.saveResource}) copies it verbatim into a server's data folder the first time this file
 * doesn't exist there yet — so those 396 overrides are live from the very first load, not merely a
 * commented-out template an operator must opt into (2026-07-26 H4 レビュー指摘: 旧Javadocとymlヘッダの
 * 「overrides: が空(既定)」という記述は出荷ファイルの実態と矛盾していたため訂正).
 *
 * <p><b>Strength resolution</b> ({@link #resolve}): 項目単位マージ, three layers cascaded in order —
 * {@code mob-profiles.yml} base &lt; {@code default} scope &lt; the specific world's scope — each layer
 * only overwriting the fields it actually sets ({@link MobStatOverride#applyTo}). A world entry that only
 * sets {@code max-health} therefore still inherits every other field from {@code default} (if any) and
 * from the base profile, never blanking them.
 *
 * <p><b>EXP resolution</b> ({@link #vanillaExpFor}): same replace-not-merge precedence as drops — the
 * world scope's {@code vanilla-exp:} ramp wins, else {@code default}'s, else "not configured" (the kill
 * keeps whatever EXP it already had). The value is a RAMP
 * ({@code base + per-level * level) * growth^(level / growth-interval)}, the very same shape
 * {@code combat/mob-import.yml} uses for every other level-dependent quantity) and is evaluated at kill
 * time against the mob's stamped combat level, so {@code level: dynamic} dungeon mobs pay out EXP that
 * follows the level the player picked on entry.
 *
 * <p><b>Drop resolution</b> ({@link #dropsFor}): REPLACE, not merge — per spec, a scope's whole
 * {@code drops:} list is used verbatim (world scope wins over default scope; neither is combined with the
 * other, and neither is combined with {@code combat/mob-level-table.yml}'s own {@code add-drops}, which
 * remains an entirely separate additive table — see {@code MobOverrideDropListener} javadoc for the
 * coexistence decision).
 */
public final class MobOverridesConfig implements LoadableConfig {

    public static final String PATH = "combat/mob-overrides.yml";
    public static final String DEFAULT_SCOPE = "default";
    private static final String CUSTOM_PREFIX = "custom:";
    /**
     * ダンジョン(スコープ)とモブの「表示名」キー (2026-07-26 「ダンジョン名とモブの表示名もGUI/簡易
     * モードで設定可能に」). config-editor が生のワールド名/EliteMobsモブidの代わりに見せる日本語名で、
     * 表示専用のメタデータ — 戦闘パイプラインもスコープ解決も一切読まない。
     */
    private static final String DISPLAY_NAME_KEY = "display-name";

    /**
     * 2026-07-26 M1 レビュー指摘の実装で判明した副次バグへの対策: このファイル限定で{@code
     * YamlConfiguration#options().pathSeparator(char)} をデフォルトの {@code '.'} から変更するための値。
     * デフォルトのままだと、YAML読み込み(convertMapsToSections → createSection)の時点でキー文字列内の
     * {@code '.'} が無条件にネストパスの区切りとして解釈され、operatorがEliteMobsのファイル名をそのまま
     * 貼った {@code "boss.yml:"} というモブidキーが {@code mobs -> boss -> yml} という3階層に分解されて
     * しまい、正規化コード({@link MobIdNormalizer})に届く前に本来の1階層のキーとして存在しなくなる
     * (skippedにもならず、中身が空のno-op overrideとして静かに失敗する)。制御文字は現実のモブid/
     * ワールド名に出現しないため区切り文字として安全に使える。
     */
    static final char MOB_ID_SAFE_PATH_SEPARATOR = (char) 1;

    private volatile Map<String, Map<String, MobOverrideEntry>> scopes = Map.of();
    private volatile Map<String, String> scopeDisplayNames = Map.of();

    public String resourcePath() {
        return PATH;
    }

    @Override
    public boolean load(Plugin plugin) {
        Logger log = plugin.getLogger();
        File file = new File(plugin.getDataFolder(), PATH);
        if (!file.exists()) {
            plugin.saveResource(PATH, false);
        }

        // loadConfiguration(File) は構文エラーを握り潰して空configを返すため自前でload()する。
        // 構文エラー時は直前に成功ロード済みの状態を維持しfalseを返す(MobLevelTableConfigと同じ流儀)。
        YamlConfiguration yaml = new YamlConfiguration();
        // 2026-07-26 M1: '.' を含むモブidキーがYAML読み込み時点で誤ってネストパス分解されないよう
        // pathSeparatorを切り替える(理由は MOB_ID_SAFE_PATH_SEPARATOR のjavadoc参照)。
        yaml.options().pathSeparator(MOB_ID_SAFE_PATH_SEPARATOR);
        try {
            yaml.load(file);
        } catch (InvalidConfigurationException | IOException ex) {
            log.log(Level.SEVERE, "[" + PATH + "] YAML構文エラーのため読み込みを中止しました。"
                    + "直前の設定値を維持します: " + ex.getMessage(), ex);
            return false;
        }

        ParseResult result = parse(yaml, log);
        this.scopes = result.scopes();
        this.scopeDisplayNames = result.scopeDisplayNames();
        if (result.skipped() > 0) {
            log.warning("[" + PATH + "] loaded " + result.mobCount() + " mob override(s), "
                    + result.skipped() + " skipped");
            return false;
        }
        log.info("[" + PATH + "] loaded " + result.mobCount() + " mob override(s) OK");
        return true;
    }

    /**
     * Applies the resolved strength override for {@code (worldName, mobId)} to {@code base}, cascading
     * default scope then the world-specific scope (each item-level, see class javadoc). Returns
     * {@code base} unchanged when no matching scope carries any stats for this mob.
     */
    public MobProfile resolve(String worldName, String mobId, MobProfile base) {
        if (base == null || mobId == null) {
            return base;
        }
        MobProfile result = base;
        result = applyScope(DEFAULT_SCOPE, mobId, result);
        String worldScope = worldScopeKey(worldName);
        if (worldScope != null) {
            result = applyScope(worldScope, mobId, result);
        }
        return result;
    }

    /**
     * The configured scope key that governs {@code worldName}, or {@code null} when none does (or when
     * the world is the {@code default} pseudo-scope, already applied separately).
     *
     * <p>An exact key match wins. Failing that, EliteMobs' instanced dungeons are matched by their
     * blueprint name: {@code WorldInstantiator#getNewWorldName} names every instance
     * {@code <blueprintWorldName>_<n>} with {@code n} incrementing for the lifetime of the server, so a
     * scope written as the literal live world name could only ever match one single instance. Writing
     * the blueprint name (e.g. {@code em_the_shattered_gate}) therefore matches every instance of that
     * dungeon ({@code ..._1}, {@code ..._2}, …). Two blueprint keys cannot both match one world (the
     * suffix must be digits only), but the longest key is still preferred so the outcome is defined by
     * the config rather than by map iteration order.
     */
    String worldScopeKey(String worldName) {
        if (worldName == null || worldName.equals(DEFAULT_SCOPE)) {
            return null;
        }
        if (scopes.containsKey(worldName)) {
            return worldName;
        }
        String best = null;
        for (String key : scopes.keySet()) {
            if (key.equals(DEFAULT_SCOPE) || !isInstanceOfBlueprint(worldName, key)) {
                continue;
            }
            if (best == null || key.length() > best.length()) {
                best = key;
            }
        }
        return best;
    }

    /** True when {@code worldName} is {@code blueprint} plus EliteMobs' {@code _<digits>} instance suffix. */
    private static boolean isInstanceOfBlueprint(String worldName, String blueprint) {
        if (blueprint.isEmpty() || worldName.length() <= blueprint.length() + 1
                || !worldName.startsWith(blueprint) || worldName.charAt(blueprint.length()) != '_') {
            return false;
        }
        for (int i = blueprint.length() + 1; i < worldName.length(); i++) {
            if (worldName.charAt(i) < '0' || worldName.charAt(i) > '9') {
                return false;
            }
        }
        return true;
    }

    private MobProfile applyScope(String scopeName, String mobId, MobProfile base) {
        Map<String, MobOverrideEntry> mobs = scopes.get(scopeName);
        if (mobs == null) {
            return base;
        }
        MobOverrideEntry entry = mobs.get(mobId);
        return entry == null ? base : entry.stats().applyTo(base);
    }

    /**
     * The replacement drop table for {@code (worldName, mobId)}: the world scope's {@code drops:} if
     * non-empty, else the {@code default} scope's, else empty (no override configured — the caller keeps
     * whatever other drop sources it already had, see class javadoc "Drop resolution").
     */
    public List<MobOverrideDropEntry> dropsFor(String worldName, String mobId) {
        if (mobId == null) {
            return List.of();
        }
        String worldScope = worldScopeKey(worldName);
        if (worldScope != null) {
            List<MobOverrideDropEntry> worldDrops = dropsInScope(worldScope, mobId);
            if (!worldDrops.isEmpty()) {
                return worldDrops;
            }
        }
        return dropsInScope(DEFAULT_SCOPE, mobId);
    }

    /**
     * The vanilla EXP this mob should drop at {@code level}, or {@link OptionalInt#empty()} when no scope
     * configures a {@code vanilla-exp:} ramp for it (caller then leaves the kill's EXP untouched — it is
     * NOT "0 EXP"). World scope wins over {@code default} scope; the two are never combined.
     *
     * <p>The result is rounded to the nearest integer and clamped to {@code >= 0} (Bukkit's
     * {@code EntityDeathEvent#setDroppedExp} rejects negative EXP, and a ramp that goes negative at some
     * level is an authoring mistake rather than a request to take EXP away).
     */
    public OptionalInt vanillaExpFor(String worldName, String mobId, int level) {
        if (mobId == null) {
            return OptionalInt.empty();
        }
        String worldScope = worldScopeKey(worldName);
        Ramp ramp = worldScope == null ? null : vanillaExpRampInScope(worldScope, mobId);
        if (ramp == null) {
            ramp = vanillaExpRampInScope(DEFAULT_SCOPE, mobId);
        }
        if (ramp == null) {
            return OptionalInt.empty();
        }
        return OptionalInt.of(toExpAmount(ramp.at(level)));
    }

    /** Rounds a ramp value to a droppable EXP amount: nearest integer, never negative, never overflowing. */
    static int toExpAmount(double rampValue) {
        if (!Double.isFinite(rampValue) || rampValue <= 0.0) {
            return 0;
        }
        return (int) Math.min(Integer.MAX_VALUE, Math.round(rampValue));
    }

    /**
     * The operator-assigned 日本語 display name for this dungeon scope, or {@link Optional#empty()}.
     * Presentation metadata for the config editor (2026-07-26); nothing in the combat pipeline reads it.
     * Resolved with the same exact-then-blueprint matching {@link #worldScopeKey} uses, so a live
     * instance world ({@code em_xxx_3}) resolves to its blueprint's name.
     */
    public Optional<String> dungeonDisplayName(String worldName) {
        String scope = worldScopeKey(worldName);
        return Optional.ofNullable(scope == null ? null : scopeDisplayNames.get(scope));
    }

    /**
     * The operator-assigned 日本語 display name for {@code (worldName, mobId)}, or
     * {@link Optional#empty()}. World scope wins over {@code default} scope, matching every other
     * replace-not-merge resolution in this file.
     */
    public Optional<String> mobDisplayName(String worldName, String mobId) {
        if (mobId == null) {
            return Optional.empty();
        }
        String id = MobIdNormalizer.normalize(mobId);
        String worldScope = worldScopeKey(worldName);
        String fromWorld = worldScope == null ? null : displayNameInScope(worldScope, id);
        return Optional.ofNullable(fromWorld != null ? fromWorld : displayNameInScope(DEFAULT_SCOPE, id));
    }

    private String displayNameInScope(String scopeName, String mobId) {
        Map<String, MobOverrideEntry> mobs = scopes.get(scopeName);
        if (mobs == null) {
            return null;
        }
        MobOverrideEntry entry = mobs.get(mobId);
        return entry == null ? null : entry.displayName();
    }

    private Ramp vanillaExpRampInScope(String scopeName, String mobId) {
        Map<String, MobOverrideEntry> mobs = scopes.get(scopeName);
        if (mobs == null) {
            return null;
        }
        MobOverrideEntry entry = mobs.get(mobId);
        return entry == null ? null : entry.vanillaExp();
    }

    private List<MobOverrideDropEntry> dropsInScope(String scopeName, String mobId) {
        Map<String, MobOverrideEntry> mobs = scopes.get(scopeName);
        if (mobs == null) {
            return List.of();
        }
        MobOverrideEntry entry = mobs.get(mobId);
        return entry == null ? List.of() : entry.drops();
    }

    /** Pure parse. Invalid entries are skipped, never fatal (mirrors {@code MobLevelTableConfig}). */
    static ParseResult parse(ConfigurationSection root, Logger log) {
        Map<String, Map<String, MobOverrideEntry>> scopes = new LinkedHashMap<>();
        int skipped = 0;
        int mobCount = 0;
        ConfigurationSection overridesSection = root == null ? null : root.getConfigurationSection("overrides");
        if (overridesSection == null) {
            return new ParseResult(Map.of(), 0, 0);
        }
        Map<String, String> scopeDisplayNames = new LinkedHashMap<>();
        for (String scopeName : overridesSection.getKeys(false)) {
            ConfigurationSection scopeSection = overridesSection.getConfigurationSection(scopeName);
            if (scopeSection == null) {
                // 2026-07-26 M2 レビュー指摘: overrides.<scopeName> がマッピングでない(値だけ書かれた等)
                // 記述ミスは、警告もskipped計上も無しに黙って読み飛ばされていた。設定漏れが「0件だがOK」
                // というログで隠れてしまう事故を防ぐため、ここで明示的に警告する。
                log.warning("[" + PATH + "] overrides." + scopeName + " is not a mapping (missing 'mobs:'?"
                        + " check indentation); this scope was skipped");
                skipped++;
                continue;
            }
            String scopeDisplayName = trimToNull(scopeSection.getString(DISPLAY_NAME_KEY));
            if (scopeDisplayName != null) {
                scopeDisplayNames.put(scopeName, scopeDisplayName);
            }
            ConfigurationSection mobsSection = scopeSection.getConfigurationSection("mobs");
            if (mobsSection == null) {
                log.warning("[" + PATH + "] overrides." + scopeName + " has no 'mobs:' section"
                        + " (forgot to nest under 'mobs:'?); this scope was skipped");
                skipped++;
                continue;
            }
            Map<String, MobOverrideEntry> mobs = new LinkedHashMap<>();
            // mobsSection.getConfigurationSection(id) は生の文字列パス経由でBukkitのpathSeparatorに
            // 従って再分割される。load() で MOB_ID_SAFE_PATH_SEPARATOR に切り替えているので通常は '.' は
            // もう区切りとして働かないが、直接 parse(ConfigurationSection, Logger) を呼ぶ経路(テスト等、
            // pathSeparatorを変更していない YamlConfiguration)でも安全なように、パス解決を経由しない
            // getValues(false)(生のトップレベルmapをそのまま返す)からキーと値を直接取り出す。
            for (Map.Entry<String, Object> mobEntry : mobsSection.getValues(false).entrySet()) {
                String rawMobId = mobEntry.getKey();
                if (!(mobEntry.getValue() instanceof ConfigurationSection mobSection)) {
                    log.warning("[" + PATH + "] " + scopeName + "." + rawMobId
                            + " is not a mapping; this mob entry was skipped");
                    skipped++;
                    continue;
                }
                // 2026-07-26 M1 レビュー指摘: ConfigManager#normalizeMobId / EliteMobs fork の
                // stripYamlExtension と同じ正規化をここでも通す。EliteMobsの getFilename() は必ず
                // ".yml" 付きで返るため、ここで揃えないと "boss.yml" スタンプと "boss" キーが
                // 噛み合わず、オーバーライドが無言で不発になる(過去に実障害を起こしたパターン)。
                String mobId = MobIdNormalizer.normalize(rawMobId);
                if (mobs.containsKey(mobId)) {
                    log.warning("[" + PATH + "] " + scopeName + "." + rawMobId
                            + " normalizes to the same id '" + mobId + "' as another entry already parsed"
                            + " in this scope; the later entry overwrites the earlier one");
                }
                StatsResult statsResult = parseStats(mobSection.getConfigurationSection("stats"), scopeName,
                        rawMobId, log);
                skipped += statsResult.skipped();
                DropsResult dropsResult = parseDrops(mobSection.getList("drops"), scopeName, rawMobId, log);
                skipped += dropsResult.skipped();
                Ramp vanillaExp = parseVanillaExp(mobSection, scopeName, rawMobId, log);
                String displayName = trimToNull(mobSection.getString(DISPLAY_NAME_KEY));
                mobs.put(mobId, new MobOverrideEntry(statsResult.stats(), dropsResult.drops(), vanillaExp,
                        displayName));
                mobCount++;
            }
            if (!mobs.isEmpty()) {
                scopes.put(scopeName, Map.copyOf(mobs));
            }
        }
        return new ParseResult(Map.copyOf(scopes), Map.copyOf(scopeDisplayNames), skipped, mobCount);
    }

    /** {@code null} for a null/blank string, the trimmed value otherwise. */
    private static String trimToNull(String raw) {
        if (raw == null) {
            return null;
        }
        String trimmed = raw.trim();
        return trimmed.isEmpty() ? null : trimmed;
    }

    /**
     * {@code vanilla-exp:} — the per-mob EXP ramp, or {@code null} when the key is absent (the normal,
     * silent case: this scope simply doesn't configure EXP for this mob).
     *
     * <p>Two authoring shortcuts are accepted so the common "flat amount" case doesn't need a section:
     * a bare number ({@code vanilla-exp: 25}) becomes a level-independent ramp
     * ({@code base=25, per-level=0}). Anything that is neither a number nor a section is a mistake —
     * warned and treated as "not configured" (fail-soft, matching {@link RampParser}'s own contract).
     */
    private static Ramp parseVanillaExp(ConfigurationSection mobSection, String scopeName, String mobId,
                                         Logger log) {
        String key = "vanilla-exp";
        if (!mobSection.contains(key)) {
            return null;
        }
        if (mobSection.isConfigurationSection(key)) {
            return RampParser.ramp(mobSection.getConfigurationSection(key));
        }
        Object raw = mobSection.get(key);
        if (raw instanceof Number number) {
            return new Ramp(number.doubleValue(), 0.0);
        }
        log.warning("[" + PATH + "] " + scopeName + "." + mobId + " vanilla-exp must be a number or a "
                + "{ base, per-level, growth, growth-interval } section; ignored");
        return null;
    }

    /**
     * 2026-07-26 H3 レビュー指摘への対応。以前は値を一切検証せず {@link MobStatOverride} を組み立てて
     * いたため、{@code level < 0} や {@code max-health < 0} を書くと {@link #resolve} 呼び出し時に
     * {@link MobProfile} のコンパクトコンストラクタが {@link IllegalArgumentException} を投げ、
     * {@code TrinityForgeSpawnListener} がそれを握りつぶして {@code stamp()} ごとスキップする —
     * つまりそのモブがTF戦闘パイプラインから丸ごと無言で外れる事故につながっていた。ここで
     * 不正な値を検出した時点で該当フィールドだけを未指定(null = 下位層の値のまま)として扱い、
     * {@code parseDrops} と同じく警告ログを出して {@code skipped} に計上する — モブ全体を巻き込まず、
     * その他の正しいフィールドは引き続き適用される。
     *
     * <p>併せて、{@link ConfigurationSection#getDouble(String)} が非数値(パース不能な文字列など)に
     * 対して警告なしで {@code 0.0} を返してしまう問題も避ける: 生の値がNumberでも数値として解釈できる
     * 文字列でもない場合は、ここで検出して警告のうえ無視する({@code toFiniteDouble}/{@code toFiniteInt}
     * を必ず経由する。生の {@code section.getDouble}/{@code getInt} を直接呼ばない)。
     */
    private static StatsResult parseStats(ConfigurationSection stats, String scopeName, String mobId, Logger log) {
        if (stats == null) {
            return new StatsResult(MobStatOverride.EMPTY, 0);
        }
        int[] skipped = {0};
        Integer level = nullableValidatedInt(stats, "level", scopeName, mobId, "stats.level", log, skipped);
        if (level != null && level < 0) {
            log.warning("[" + PATH + "] " + scopeName + "." + mobId + " stats.level must be >= 0 (was "
                    + level + "); ignored");
            skipped[0]++;
            level = null;
        }
        Double maxHealth = nullableValidatedDouble(stats, "max-health", scopeName, mobId, "stats.max-health",
                log, skipped);
        if (maxHealth != null && maxHealth < 0) {
            log.warning("[" + PATH + "] " + scopeName + "." + mobId + " stats.max-health must be >= 0 (was "
                    + maxHealth + "); ignored");
            skipped[0]++;
            maxHealth = null;
        }
        Double armorStrength = nullableValidatedDouble(stats, "armor-strength", scopeName, mobId,
                "stats.armor-strength", log, skipped);
        MobStatOverride.DefenseFieldOverride physical =
                parseDefense(stats.getConfigurationSection("physical"), scopeName, mobId, "physical", log, skipped);
        MobStatOverride.DefenseFieldOverride magical =
                parseDefense(stats.getConfigurationSection("magical"), scopeName, mobId, "magical", log, skipped);
        MobStatOverride.AttackFieldOverride attack =
                parseAttack(stats.getConfigurationSection("attack"), scopeName, mobId, log, skipped);
        MobStatOverride result = new MobStatOverride(level, maxHealth, armorStrength, physical, magical, attack);
        return new StatsResult(result, skipped[0]);
    }

    private static MobStatOverride.DefenseFieldOverride parseDefense(ConfigurationSection section,
            String scopeName, String mobId, String fieldPrefix, Logger log, int[] skipped) {
        if (section == null) {
            return null;
        }
        return new MobStatOverride.DefenseFieldOverride(
                nullableValidatedDouble(section, "defense-rate", scopeName, mobId,
                        "stats." + fieldPrefix + ".defense-rate", log, skipped),
                nullableValidatedDouble(section, "resistance", scopeName, mobId,
                        "stats." + fieldPrefix + ".resistance", log, skipped),
                nullableValidatedDouble(section, "damage-reduction", scopeName, mobId,
                        "stats." + fieldPrefix + ".damage-reduction", log, skipped),
                nullableValidatedDouble(section, "flat-defense", scopeName, mobId,
                        "stats." + fieldPrefix + ".flat-defense", log, skipped));
    }

    private static MobStatOverride.AttackFieldOverride parseAttack(ConfigurationSection section,
            String scopeName, String mobId, Logger log, int[] skipped) {
        if (section == null) {
            return null;
        }
        return new MobStatOverride.AttackFieldOverride(
                // "attack-power" (not "default-damage"): matches combat/mob-profiles.yml's/
                // combat/mob-types.yml's own attack: key vocabulary for this same AttackStats.defaultDamage
                // field (2026-07-26 spec要件「mob-profiles.ymlと同じキー体系にすること」).
                nullableValidatedDouble(section, "attack-power", scopeName, mobId, "stats.attack.attack-power",
                        log, skipped),
                nullableValidatedDouble(section, "flat-bonus-damage", scopeName, mobId,
                        "stats.attack.flat-bonus-damage", log, skipped),
                nullableValidatedDouble(section, "percent-bonus-damage", scopeName, mobId,
                        "stats.attack.percent-bonus-damage", log, skipped),
                nullableValidatedDouble(section, "crit-chance", scopeName, mobId, "stats.attack.crit-chance",
                        log, skipped),
                nullableValidatedDouble(section, "crit-damage", scopeName, mobId, "stats.attack.crit-damage",
                        log, skipped),
                nullableValidatedDouble(section, "penetration", scopeName, mobId, "stats.attack.penetration",
                        log, skipped),
                nullableValidatedDouble(section, "damage-modifier", scopeName, mobId,
                        "stats.attack.damage-modifier", log, skipped),
                nullableValidatedDouble(section, "fixed-damage", scopeName, mobId, "stats.attack.fixed-damage",
                        log, skipped));
    }

    /**
     * {@code null} when the key is absent (silent — normal "not overridden" case). When present but the
     * raw value is neither a {@link Number} nor a numeric string, warns and returns {@code null} instead
     * of silently falling back to {@code 0.0} the way {@link ConfigurationSection#getDouble(String)}
     * does on its own.
     */
    private static Double nullableValidatedDouble(ConfigurationSection section, String key, String scopeName,
            String mobId, String fieldLabel, Logger log, int[] skipped) {
        if (!section.contains(key)) {
            return null;
        }
        Object raw = section.get(key);
        Double value = toFiniteDouble(raw);
        if (value == null) {
            log.warning("[" + PATH + "] " + scopeName + "." + mobId + " " + fieldLabel
                    + " must be numeric (was '" + raw + "'); ignored");
            skipped[0]++;
        }
        return value;
    }

    /** Same contract as {@link #nullableValidatedDouble}, integer-valued. */
    private static Integer nullableValidatedInt(ConfigurationSection section, String key, String scopeName,
            String mobId, String fieldLabel, Logger log, int[] skipped) {
        if (!section.contains(key)) {
            return null;
        }
        Object raw = section.get(key);
        Integer value = toFiniteInt(raw);
        if (value == null) {
            log.warning("[" + PATH + "] " + scopeName + "." + mobId + " " + fieldLabel
                    + " must be an integer (was '" + raw + "'); ignored");
            skipped[0]++;
        }
        return value;
    }

    private static Double toFiniteDouble(Object raw) {
        if (raw instanceof Number number) {
            double value = number.doubleValue();
            return Double.isFinite(value) ? value : null;
        }
        if (raw instanceof String str) {
            try {
                double value = Double.parseDouble(str.trim());
                return Double.isFinite(value) ? value : null;
            } catch (NumberFormatException ex) {
                return null;
            }
        }
        return null;
    }

    private static Integer toFiniteInt(Object raw) {
        if (raw instanceof Number number) {
            return number.intValue();
        }
        if (raw instanceof String str) {
            try {
                return Integer.parseInt(str.trim());
            } catch (NumberFormatException ex) {
                return null;
            }
        }
        return null;
    }

    private static DropsResult parseDrops(List<?> raw, String scopeName, String mobId, Logger log) {
        java.util.List<MobOverrideDropEntry> drops = new java.util.ArrayList<>();
        int skipped = 0;
        if (raw == null) {
            return new DropsResult(drops, 0);
        }
        for (Object item : raw) {
            if (!(item instanceof Map<?, ?> map)) {
                log.warning("[" + PATH + "] " + scopeName + "." + mobId + " drops has a non-mapping entry; skipped");
                skipped++;
                continue;
            }
            Object itemRaw = map.get("item");
            if (itemRaw == null) {
                log.warning("[" + PATH + "] " + scopeName + "." + mobId + " drops entry missing 'item'; skipped");
                skipped++;
                continue;
            }
            String token = String.valueOf(itemRaw).trim();
            Material material = null;
            String catalogId = null;
            if (token.regionMatches(true, 0, CUSTOM_PREFIX, 0, CUSTOM_PREFIX.length())) {
                catalogId = token.substring(CUSTOM_PREFIX.length()).trim();
                if (catalogId.isEmpty()) {
                    log.warning("[" + PATH + "] " + scopeName + "." + mobId
                            + " drops 'custom:' id must not be blank; skipped");
                    skipped++;
                    continue;
                }
            } else {
                try {
                    material = Material.valueOf(token.toUpperCase(Locale.ROOT));
                } catch (IllegalArgumentException ex) {
                    log.warning("[" + PATH + "] " + scopeName + "." + mobId + " drops item '" + token
                            + "' invalid; skipped");
                    skipped++;
                    continue;
                }
            }
            try {
                double chance = clamp01(requireDouble(map, "chance"));
                int min = requireInt(map, "min");
                int max = requireInt(map, "max");
                drops.add(catalogId != null
                        ? MobOverrideDropEntry.ofCatalog(catalogId, chance, min, max)
                        : MobOverrideDropEntry.ofMaterial(material, chance, min, max));
            } catch (IllegalArgumentException ex) {
                log.warning("[" + PATH + "] " + scopeName + "." + mobId + " drops for " + token + " invalid ("
                        + ex.getMessage() + "); skipped");
                skipped++;
            }
        }
        return new DropsResult(drops, skipped);
    }

    private static double requireDouble(Map<?, ?> raw, String field) {
        Object value = raw.get(field);
        if (!(value instanceof Number number)) {
            throw new IllegalArgumentException("'" + field + "' is required and must be numeric");
        }
        return number.doubleValue();
    }

    private static int requireInt(Map<?, ?> raw, String field) {
        Object value = raw.get(field);
        if (!(value instanceof Number number)) {
            throw new IllegalArgumentException("'" + field + "' is required and must be numeric");
        }
        return number.intValue();
    }

    private static double clamp01(double value) {
        return Math.max(0.0, Math.min(1.0, value));
    }

    /** Parse outcome: the immutable scope map and how many mob entries/drops were skipped. */
    record ParseResult(Map<String, Map<String, MobOverrideEntry>> scopes,
                       Map<String, String> scopeDisplayNames, int skipped, int mobCount) {

        /** Back-compat for tests written before ダンジョン表示名 (2026-07-26) existed. */
        ParseResult(Map<String, Map<String, MobOverrideEntry>> scopes, int skipped, int mobCount) {
            this(scopes, Map.of(), skipped, mobCount);
        }
    }

    private record DropsResult(List<MobOverrideDropEntry> drops, int skipped) {
    }

    /** Parse outcome for one mob's {@code stats:} block: the merged override plus how many of its
     *  individual fields were invalid and dropped (2026-07-26 H3). */
    private record StatsResult(MobStatOverride stats, int skipped) {
    }
}
