package com.trinityforge.config.domains;

import com.trinityforge.config.LoadableConfig;
import com.trinityforge.mobs.ConversionPolicy.Ramp;
import com.trinityforge.mobs.MobIdNormalizer;
import com.trinityforge.mobs.MobOverrideDropEntry;
import com.trinityforge.mobs.MobOverrideEntry;
import com.trinityforge.mobs.MobProfile;
import com.trinityforge.mobs.MobStatOverride;
import com.trinityforge.mobs.RampParser;
import org.bukkit.Material;
import org.bukkit.configuration.ConfigurationSection;
import org.bukkit.configuration.InvalidConfigurationException;
import org.bukkit.configuration.file.YamlConfiguration;
import org.bukkit.plugin.Plugin;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Optional;
import java.util.OptionalInt;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * Loader for {@code combat/mob-overrides.yml} (2026-07-26 「エリートモブズインスタンス内のカスタムモブ
 * ごとに個別のドロップテーブルと強さテーブルを設定できる」要望): a "ダンジョン(ワールド) × モブid" overlay
 * layered ON TOP of the autogenerated {@code combat/mob-profiles.yml} (never edited by this feature —
 * {@code /trinityforge importmobs} owns that file and would wipe hand edits on re-import).
 *
 * <p><b>Structure</b>: {@code overrides.<worldName>.mobs.<mobId>} for a world-specific entry, or
 * {@code overrides.default.mobs.<mobId>} for the全ダンジョン共通フォールバック. The world key may be either
 * the live world name or an instanced dungeon's blueprint world name, which then covers every instance
 * of that dungeon — see {@link #worldScopeKey}. {@code overrides:} absent or empty is a LOGICAL no-op
 * ({@link #resolve} always returns {@code base} unchanged and {@link #dropsFor}/{@link #vanillaExpFor}
 * always return empty) — but that is a code guarantee, not a description of the shipped resource file.
 * <b>The shipped {@code combat/mob-overrides.yml} is NOT empty</b>: as of 2026-07-26 it ships with
 * {@code overrides:} already populated for 396 dungeon mobs, and {@link #load} (via
 * {@code plugin.saveResource}) copies it verbatim into a server's data folder the first time this file
 * doesn't exist there yet — so those 396 overrides are live from the very first load, not merely a
 * commented-out template an operator must opt into (2026-07-26 H4 レビュー指摘: 旧Javadocとymlヘッダの
 * 「overrides: が空(既定)」という記述は出荷ファイルの実態と矛盾していたため訂正).
 *
 * <p><b>Strength resolution</b> ({@link #resolve}): 項目単位マージ, five layers cascaded in order —
 * {@code mob-profiles.yml} base &lt; {@code default} の scope 直下 &lt; {@code default} の mob 単位
 * &lt; the specific world's scope 直下 &lt; that world's mob 単位 — each layer only overwriting the fields
 * it actually sets ({@link MobStatOverride#applyTo}). A world entry that only sets {@code max-health}
 * therefore still inherits every other field from {@code default} (if any) and from the base profile,
 * never blanking them.
 *
 * <p><b>scope 直下の {@code stats:}</b> (2026-08-03 「ダンジョンごとに物魔のコンセプトを割り当てる」要望):
 * {@code overrides.<worldName>.stats:} は {@code mobs:} と同じ階層に書く「そのダンジョン全体の既定値」で、
 * キー体系は {@code mobs.<mobId>.stats} と完全に同一(同じ {@code parseStats} を通す)。これがある理由は、
 * ダンジョンの敵は 396 体あり「このダンジョンの敵は魔法型」といったコンセプトを 1 体ずつ書くのは非現実的
 * だから。解決は<b>項目単位マージ</b>である — scope 直下で {@code attack.magic-ratio} だけ書き、
 * 特定のモブだけ {@code mobs.<id>.stats.max-health} を上書きする、という重ね方が意図した使い方。
 *
 * <p><b>倍率キー {@code max-health-multiplier} / {@code attack-power-multiplier}</b>
 * (2026-08-14 「ダンジョンの難易度を敵の強さの差で表現する」要望): {@code stats:} 直下に書く
 * 「元の値の何倍にするか」。絶対値と併記した場合は<b>絶対値を先に適用し、その結果に倍率を掛ける</b>
 * (適用順序の仕様は {@link MobStatOverride#applyTo} の javadoc)。難易度をこれで表現するのは、
 * ダイナミックダンジョン(プレイヤーが入場時にレベルを選ぶ)では絶対値が使えないため —— 倍率なら
 * 「選んだレベルで本来決まる強さの N 倍」という相対差として成立する。値は<b>0 より大きい有限数</b>
 * のみ有効(理由は {@code nullablePositiveMultiplier} の javadoc)。<b>倍率だけは 4 層のカスケードで
 * 「後勝ち」ではなく掛け合わさる</b>({@link #resolve} が層ごとに {@code applyTo} を呼ぶため) ——
 * {@code default} に書いた倍率は全ダンジョンに乗るので、ダンジョン間の差だけを付けたいなら
 * {@code default} には書かない。
 *
 * <p><b>EXP resolution</b> ({@link #vanillaExpFor}): same replace-not-merge precedence as drops — the
 * world scope's {@code vanilla-exp:} ramp wins, else {@code default}'s, else "not configured" (the kill
 * keeps whatever EXP it already had). The value is a RAMP
 * ({@code base + per-level * level) * growth^(level / growth-interval)}, the very same shape
 * {@code combat/mob-import.yml} uses for every other level-dependent quantity) and is evaluated at kill
 * time against the mob's stamped combat level, so {@code level: dynamic} dungeon mobs pay out EXP that
 * follows the level the player picked on entry.
 *
 * <p><b>Drop resolution</b> ({@link #dropsFor}): REPLACE, not merge — per spec, a scope's whole
 * {@code drops:} list is used verbatim (world scope wins over default scope; neither is combined with the
 * other, and neither is combined with {@code combat/mob-level-table.yml}'s own {@code add-drops}, which
 * remains an entirely separate additive table — see {@code MobOverrideDropListener} javadoc for the
 * coexistence decision).
 *
 * <p><b>「レベル差による足きり」はこのファイルには無い(2026-08-09 撤去)。</b> 2026-07-27 に
 * {@code level-cutoff:} を scope 直下 / mob 単位の 4 段カスケードとしてここに実装したが、この設定は
 * <b>EliteMobs が {@code MOB_PROFILE_ID} をスタンプしたモブ(= ダンジョンモブ)にしか掛からない</b>
 * という構造的な穴があった — フィールドの野良モブはどれだけレベル差があっても素通りしていた。
 * 全モブ共通の設定として {@code combat/damage.yml} の {@code level-cutoff:} へ移し、適用は
 * {@code com.trinityforge.listeners.KillRewardAdjuster} 一点に集約している。ダンジョン別に足きりを
 * 変える機能は<b>意図的に落とした</b>(ダンジョンへの入場制限は {@code dungeon/gates.yml} の
 * {@code required-combat-level} が担当する)。
 */
public final class MobOverridesConfig implements LoadableConfig {

    public static final String PATH = "combat/mob-overrides.yml";
    public static final String DEFAULT_SCOPE = "default";
    private static final String CUSTOM_PREFIX = "custom:";
    /**
     * ダンジョン(スコープ)とモブの「表示名」キー (2026-07-26 「ダンジョン名とモブの表示名もGUI/簡易
     * モードで設定可能に」). config-editor が生のワールド名/EliteMobsモブidの代わりに見せる日本語名で、
     * 表示専用のメタデータ — 戦闘パイプラインもスコープ解決も一切読まない。
     */
    private static final String DISPLAY_NAME_KEY = "display-name";
    /** 特殊攻撃テンプレートIDの列(2026-07-31)。値は combat/mob-abilities.yml のキー。 */
    private static final String ABILITIES_KEY = "abilities";

    /**
     * 2026-07-26 M1 レビュー指摘の実装で判明した副次バグへの対策: このファイル限定で{@code
     * YamlConfiguration#options().pathSeparator(char)} をデフォルトの {@code '.'} から変更するための値。
     * デフォルトのままだと、YAML読み込み(convertMapsToSections → createSection)の時点でキー文字列内の
     * {@code '.'} が無条件にネストパスの区切りとして解釈され、operatorがEliteMobsのファイル名をそのまま
     * 貼った {@code "boss.yml:"} というモブidキーが {@code mobs -> boss -> yml} という3階層に分解されて
     * しまい、正規化コード({@link MobIdNormalizer})に届く前に本来の1階層のキーとして存在しなくなる
     * (skippedにもならず、中身が空のno-op overrideとして静かに失敗する)。制御文字は現実のモブid/
     * ワールド名に出現しないため区切り文字として安全に使える。
     */
    static final char MOB_ID_SAFE_PATH_SEPARATOR = (char) 1;

    private volatile Map<String, Map<String, MobOverrideEntry>> scopes = Map.of();
    private volatile Map<String, String> scopeDisplayNames = Map.of();
    /** scope 直下の {@code stats:}(そのダンジョン全体の既定ステータス、2026-08-03)。class javadoc 参照。 */
    private volatile Map<String, MobStatOverride> scopeStats = Map.of();

    public String resourcePath() {
        return PATH;
    }

    @Override
    public boolean load(Plugin plugin) {
        Logger log = plugin.getLogger();
        File file = new File(plugin.getDataFolder(), PATH);
        if (!file.exists()) {
            plugin.saveResource(PATH, false);
        }

        // loadConfiguration(File) は構文エラーを握り潰して空configを返すため自前でload()する。
        // 構文エラー時は直前に成功ロード済みの状態を維持しfalseを返す(MobLevelTableConfigと同じ流儀)。
        YamlConfiguration yaml = new YamlConfiguration();
        // 2026-07-26 M1: '.' を含むモブidキーがYAML読み込み時点で誤ってネストパス分解されないよう
        // pathSeparatorを切り替える(理由は MOB_ID_SAFE_PATH_SEPARATOR のjavadoc参照)。
        yaml.options().pathSeparator(MOB_ID_SAFE_PATH_SEPARATOR);
        try {
            yaml.load(file);
        } catch (InvalidConfigurationException | IOException ex) {
            log.log(Level.SEVERE, "[" + PATH + "] YAML構文エラーのため読み込みを中止しました。"
                    + "直前の設定値を維持します: " + ex.getMessage(), ex);
            return false;
        }

        ParseResult result = parse(yaml, log);
        this.scopes = result.scopes();
        this.scopeDisplayNames = result.scopeDisplayNames();
        this.scopeStats = result.scopeStats();
        if (result.skipped() > 0) {
            log.warning("[" + PATH + "] loaded " + result.mobCount() + " mob override(s), "
                    + result.skipped() + " skipped");
            return false;
        }
        log.info("[" + PATH + "] loaded " + result.mobCount() + " mob override(s) OK");
        return true;
    }

    /**
     * Applies the resolved strength override for {@code (worldName, mobId)} to {@code base}, cascading
     * default scope then the world-specific scope, and within each scope its 直下 {@code stats:} before
     * its mob 単位 entry (each item-level, see class javadoc). Returns {@code base} unchanged when no
     * matching scope carries any stats for this mob.
     */
    public MobProfile resolve(String worldName, String mobId, MobProfile base) {
        if (base == null || mobId == null) {
            return base;
        }
        MobProfile result = base;
        result = applyScopeDefaults(DEFAULT_SCOPE, result);
        result = applyScope(DEFAULT_SCOPE, mobId, result);
        String worldScope = worldScopeKey(worldName);
        if (worldScope != null) {
            result = applyScopeDefaults(worldScope, result);
            result = applyScope(worldScope, mobId, result);
        }
        return result;
    }

    /**
     * The configured scope key that governs {@code worldName}, or {@code null} when none does (or when
     * the world is the {@code default} pseudo-scope, already applied separately).
     *
     * <p>An exact key match wins. Failing that, EliteMobs' instanced dungeons are matched by their
     * blueprint name: {@code WorldInstantiator#getNewWorldName} names every instance
     * {@code <blueprintWorldName>_<n>} with {@code n} incrementing for the lifetime of the server, so a
     * scope written as the literal live world name could only ever match one single instance. Writing
     * the blueprint name (e.g. {@code em_the_shattered_gate}) therefore matches every instance of that
     * dungeon ({@code ..._1}, {@code ..._2}, …). Two blueprint keys cannot both match one world (the
     * suffix must be digits only), but the longest key is still preferred so the outcome is defined by
     * the config rather than by map iteration order.
     */
    String worldScopeKey(String worldName) {
        if (worldName == null || worldName.equals(DEFAULT_SCOPE)) {
            return null;
        }
        // 2026-08-03: scopes(mob単位のエントリを持つscope)だけでなく、scope直下にしか設定が無いscope
        // (stats: / level-cutoff: だけ書いたダンジョン)も候補に含める。ここを scopes だけで見ていると、
        // 「mobs: を1件も書かずダンジョン全体のコンセプトだけ指定した」scope が無言で一致しなくなる。
        Set<String> candidates = knownScopeKeys();
        if (candidates.contains(worldName)) {
            return worldName;
        }
        String best = null;
        for (String key : candidates) {
            if (key.equals(DEFAULT_SCOPE) || !isInstanceOfBlueprint(worldName, key)) {
                continue;
            }
            if (best == null || key.length() > best.length()) {
                best = key;
            }
        }
        return best;
    }

    /** 何らかの設定を持つ scope 名すべて(mob単位 / scope直下 stats の和集合)。 */
    private Set<String> knownScopeKeys() {
        Set<String> keys = new LinkedHashSet<>(scopes.keySet());
        keys.addAll(scopeStats.keySet());
        return keys;
    }

    /** True when {@code worldName} is {@code blueprint} plus EliteMobs' {@code _<digits>} instance suffix. */
    private static boolean isInstanceOfBlueprint(String worldName, String blueprint) {
        if (blueprint.isEmpty() || worldName.length() <= blueprint.length() + 1
                || !worldName.startsWith(blueprint) || worldName.charAt(blueprint.length()) != '_') {
            return false;
        }
        for (int i = blueprint.length() + 1; i < worldName.length(); i++) {
            if (worldName.charAt(i) < '0' || worldName.charAt(i) > '9') {
                return false;
            }
        }
        return true;
    }

    private MobProfile applyScope(String scopeName, String mobId, MobProfile base) {
        Map<String, MobOverrideEntry> mobs = scopes.get(scopeName);
        if (mobs == null) {
            return base;
        }
        MobOverrideEntry entry = mobs.get(mobId);
        return entry == null ? base : entry.stats().applyTo(base);
    }

    /**
     * scope 直下の {@code stats:}(そのダンジョン全体の既定)を適用する。mob 単位のエントリが
     * <b>無い</b>モブにも効くのがこの層の存在意義 —— ダンジョン内の全モブに一括でコンセプト
     * (物理型/魔法型)を乗せるために使う。
     */
    private MobProfile applyScopeDefaults(String scopeName, MobProfile base) {
        MobStatOverride override = scopeStats.get(scopeName);
        return override == null ? base : override.applyTo(base);
    }

    /**
     * The replacement drop table for {@code (worldName, mobId)}: the world scope's {@code drops:} if
     * non-empty, else the {@code default} scope's, else empty (no override configured — the caller keeps
     * whatever other drop sources it already had, see class javadoc "Drop resolution").
     */
    public List<MobOverrideDropEntry> dropsFor(String worldName, String mobId) {
        if (mobId == null) {
            return List.of();
        }
        String worldScope = worldScopeKey(worldName);
        if (worldScope != null) {
            List<MobOverrideDropEntry> worldDrops = dropsInScope(worldScope, mobId);
            if (!worldDrops.isEmpty()) {
                return worldDrops;
            }
        }
        return dropsInScope(DEFAULT_SCOPE, mobId);
    }

    /**
     * The vanilla EXP this mob should drop at {@code level}, or {@link OptionalInt#empty()} when no scope
     * configures a {@code vanilla-exp:} ramp for it (caller then leaves the kill's EXP untouched — it is
     * NOT "0 EXP"). World scope wins over {@code default} scope; the two are never combined.
     *
     * <p>The result is rounded to the nearest integer and clamped to {@code >= 0} (Bukkit's
     * {@code EntityDeathEvent#setDroppedExp} rejects negative EXP, and a ramp that goes negative at some
     * level is an authoring mistake rather than a request to take EXP away).
     */
    public OptionalInt vanillaExpFor(String worldName, String mobId, int level) {
        if (mobId == null) {
            return OptionalInt.empty();
        }
        String worldScope = worldScopeKey(worldName);
        Ramp ramp = worldScope == null ? null : vanillaExpRampInScope(worldScope, mobId);
        if (ramp == null) {
            ramp = vanillaExpRampInScope(DEFAULT_SCOPE, mobId);
        }
        if (ramp == null) {
            return OptionalInt.empty();
        }
        return OptionalInt.of(toExpAmount(ramp.at(level)));
    }

    /** Rounds a ramp value to a droppable EXP amount: nearest integer, never negative, never overflowing. */
    static int toExpAmount(double rampValue) {
        if (!Double.isFinite(rampValue) || rampValue <= 0.0) {
            return 0;
        }
        return (int) Math.min(Integer.MAX_VALUE, Math.round(rampValue));
    }

    /**
     * The operator-assigned 日本語 display name for this dungeon scope, or {@link Optional#empty()}.
     * Presentation metadata for the config editor (2026-07-26); nothing in the combat pipeline reads it.
     * Resolved with the same exact-then-blueprint matching {@link #worldScopeKey} uses, so a live
     * instance world ({@code em_xxx_3}) resolves to its blueprint's name.
     */
    public Optional<String> dungeonDisplayName(String worldName) {
        String scope = worldScopeKey(worldName);
        return Optional.ofNullable(scope == null ? null : scopeDisplayNames.get(scope));
    }

    /**
     * The operator-assigned 日本語 display name for {@code (worldName, mobId)}, or
     * {@link Optional#empty()}. World scope wins over {@code default} scope, matching every other
     * replace-not-merge resolution in this file.
     */
    public Optional<String> mobDisplayName(String worldName, String mobId) {
        if (mobId == null) {
            return Optional.empty();
        }
        String id = MobIdNormalizer.normalize(mobId);
        String worldScope = worldScopeKey(worldName);
        String fromWorld = worldScope == null ? null : displayNameInScope(worldScope, id);
        return Optional.ofNullable(fromWorld != null ? fromWorld : displayNameInScope(DEFAULT_SCOPE, id));
    }

    private String displayNameInScope(String scopeName, String mobId) {
        Map<String, MobOverrideEntry> mobs = scopes.get(scopeName);
        if (mobs == null) {
            return null;
        }
        MobOverrideEntry entry = mobs.get(mobId);
        return entry == null ? null : entry.displayName();
    }

    private Ramp vanillaExpRampInScope(String scopeName, String mobId) {
        Map<String, MobOverrideEntry> mobs = scopes.get(scopeName);
        if (mobs == null) {
            return null;
        }
        MobOverrideEntry entry = mobs.get(mobId);
        return entry == null ? null : entry.vanillaExp();
    }

    /**
     * このモブが撃つ特殊攻撃テンプレートIDの列(2026-07-31)。解決規則は {@link #dropsFor} と同じ
     * REPLACE — ワールドスコープが1件でも書いていればそれが全部で、default 側とは合成しない
     * (合成すると「ダンジョンごとに技を差し替える」ができなくなる)。
     */
    public List<String> abilitiesFor(String worldName, String mobId) {
        if (mobId == null) {
            return List.of();
        }
        String id = MobIdNormalizer.normalize(mobId);
        String worldScope = worldScopeKey(worldName);
        if (worldScope != null) {
            List<String> worldAbilities = abilitiesInScope(worldScope, id);
            if (!worldAbilities.isEmpty()) {
                return worldAbilities;
            }
        }
        return abilitiesInScope(DEFAULT_SCOPE, id);
    }

    private List<String> abilitiesInScope(String scopeName, String mobId) {
        Map<String, MobOverrideEntry> mobs = scopes.get(scopeName);
        if (mobs == null) {
            return List.of();
        }
        MobOverrideEntry entry = mobs.get(mobId);
        return entry == null ? List.of() : entry.abilities();
    }

    private List<MobOverrideDropEntry> dropsInScope(String scopeName, String mobId) {
        Map<String, MobOverrideEntry> mobs = scopes.get(scopeName);
        if (mobs == null) {
            return List.of();
        }
        MobOverrideEntry entry = mobs.get(mobId);
        return entry == null ? List.of() : entry.drops();
    }

    /** Pure parse. Invalid entries are skipped, never fatal (mirrors {@code MobLevelTableConfig}). */
    static ParseResult parse(ConfigurationSection root, Logger log) {
        Map<String, Map<String, MobOverrideEntry>> scopes = new LinkedHashMap<>();
        int skipped = 0;
        int mobCount = 0;
        ConfigurationSection overridesSection = root == null ? null : root.getConfigurationSection("overrides");
        if (overridesSection == null) {
            return new ParseResult(Map.of(), 0, 0);
        }
        Map<String, String> scopeDisplayNames = new LinkedHashMap<>();
        Map<String, MobStatOverride> scopeStats = new LinkedHashMap<>();
        for (String scopeName : overridesSection.getKeys(false)) {
            ConfigurationSection scopeSection = overridesSection.getConfigurationSection(scopeName);
            if (scopeSection == null) {
                // 2026-07-26 M2 レビュー指摘: overrides.<scopeName> がマッピングでない(値だけ書かれた等)
                // 記述ミスは、警告もskipped計上も無しに黙って読み飛ばされていた。設定漏れが「0件だがOK」
                // というログで隠れてしまう事故を防ぐため、ここで明示的に警告する。
                log.warning("[" + PATH + "] overrides." + scopeName + " is not a mapping (missing 'mobs:'?"
                        + " check indentation); this scope was skipped");
                skipped++;
                continue;
            }
            String scopeDisplayName = trimToNull(scopeSection.getString(DISPLAY_NAME_KEY));
            if (scopeDisplayName != null) {
                scopeDisplayNames.put(scopeName, scopeDisplayName);
            }
            // scope 直下の stats:(ダンジョン全体の既定値、2026-08-03)。mob 単位とまったく同じパーサを
            // 通すのでキー体系も検証もズレようがない。
            StatsResult scopeStatsResult = parseStats(scopeSection.getConfigurationSection("stats"), scopeName,
                    "<scope>", log);
            skipped += scopeStatsResult.skipped();
            if (!scopeStatsResult.stats().isEmpty()) {
                scopeStats.put(scopeName, scopeStatsResult.stats());
            }
            ConfigurationSection mobsSection = scopeSection.getConfigurationSection("mobs");
            if (mobsSection == null) {
                // 2026-08-03: scope直下だけで完結する設定(stats:)を書いた場合は 'mobs:' が無くても
                // 正しい記述なので警告しない。それも無いときだけ書き間違いとして扱う。
                if (scopeStatsResult.stats().isEmpty()) {
                    log.warning("[" + PATH + "] overrides." + scopeName + " has no 'mobs:' section"
                            + " (forgot to nest under 'mobs:'?); this scope was skipped");
                    skipped++;
                }
                continue;
            }
            Map<String, MobOverrideEntry> mobs = new LinkedHashMap<>();
            // mobsSection.getConfigurationSection(id) は生の文字列パス経由でBukkitのpathSeparatorに
            // 従って再分割される。load() で MOB_ID_SAFE_PATH_SEPARATOR に切り替えているので通常は '.' は
            // もう区切りとして働かないが、直接 parse(ConfigurationSection, Logger) を呼ぶ経路(テスト等、
            // pathSeparatorを変更していない YamlConfiguration)でも安全なように、パス解決を経由しない
            // getValues(false)(生のトップレベルmapをそのまま返す)からキーと値を直接取り出す。
            for (Map.Entry<String, Object> mobEntry : mobsSection.getValues(false).entrySet()) {
                String rawMobId = mobEntry.getKey();
                if (!(mobEntry.getValue() instanceof ConfigurationSection mobSection)) {
                    log.warning("[" + PATH + "] " + scopeName + "." + rawMobId
                            + " is not a mapping; this mob entry was skipped");
                    skipped++;
                    continue;
                }
                // 2026-07-26 M1 レビュー指摘: ConfigManager#normalizeMobId / EliteMobs fork の
                // stripYamlExtension と同じ正規化をここでも通す。EliteMobsの getFilename() は必ず
                // ".yml" 付きで返るため、ここで揃えないと "boss.yml" スタンプと "boss" キーが
                // 噛み合わず、オーバーライドが無言で不発になる(過去に実障害を起こしたパターン)。
                String mobId = MobIdNormalizer.normalize(rawMobId);
                if (mobs.containsKey(mobId)) {
                    log.warning("[" + PATH + "] " + scopeName + "." + rawMobId
                            + " normalizes to the same id '" + mobId + "' as another entry already parsed"
                            + " in this scope; the later entry overwrites the earlier one");
                }
                StatsResult statsResult = parseStats(mobSection.getConfigurationSection("stats"), scopeName,
                        rawMobId, log);
                skipped += statsResult.skipped();
                DropsResult dropsResult = parseDrops(mobSection.getList("drops"), scopeName, rawMobId, log);
                skipped += dropsResult.skipped();
                Ramp vanillaExp = parseVanillaExp(mobSection, scopeName, rawMobId, log);
                String displayName = trimToNull(mobSection.getString(DISPLAY_NAME_KEY));
                // 2026-07-31: 特殊攻撃テンプレートIDの列。ここでは実在チェックをしない ——
                // mob-abilities.yml のロード順に依存させたくないため。未定義IDは発動時に読み飛ばす。
                List<String> abilities = new ArrayList<>();
                for (String raw : mobSection.getStringList(ABILITIES_KEY)) {
                    if (raw != null && !raw.isBlank()) {
                        String normalized = raw.trim().toLowerCase(java.util.Locale.ROOT);
                        if (!abilities.contains(normalized)) {
                            abilities.add(normalized);
                        }
                    }
                }
                mobs.put(mobId, new MobOverrideEntry(statsResult.stats(), dropsResult.drops(), vanillaExp,
                        displayName, abilities));
                mobCount++;
            }
            if (!mobs.isEmpty()) {
                scopes.put(scopeName, Map.copyOf(mobs));
            }
        }
        return new ParseResult(Map.copyOf(scopes), Map.copyOf(scopeDisplayNames),
                Map.copyOf(scopeStats), skipped, mobCount);
    }

    /** {@code null} for a null/blank string, the trimmed value otherwise. */
    private static String trimToNull(String raw) {
        if (raw == null) {
            return null;
        }
        String trimmed = raw.trim();
        return trimmed.isEmpty() ? null : trimmed;
    }

    /**
     * {@code vanilla-exp:} — the per-mob EXP ramp, or {@code null} when the key is absent (the normal,
     * silent case: this scope simply doesn't configure EXP for this mob).
     *
     * <p>Two authoring shortcuts are accepted so the common "flat amount" case doesn't need a section:
     * a bare number ({@code vanilla-exp: 25}) becomes a level-independent ramp
     * ({@code base=25, per-level=0}). Anything that is neither a number nor a section is a mistake —
     * warned and treated as "not configured" (fail-soft, matching {@link RampParser}'s own contract).
     */
    private static Ramp parseVanillaExp(ConfigurationSection mobSection, String scopeName, String mobId,
                                         Logger log) {
        String key = "vanilla-exp";
        if (!mobSection.contains(key)) {
            return null;
        }
        if (mobSection.isConfigurationSection(key)) {
            return RampParser.ramp(mobSection.getConfigurationSection(key));
        }
        Object raw = mobSection.get(key);
        if (raw instanceof Number number) {
            return new Ramp(number.doubleValue(), 0.0);
        }
        log.warning("[" + PATH + "] " + scopeName + "." + mobId + " vanilla-exp must be a number or a "
                + "{ base, per-level, growth, growth-interval } section; ignored");
        return null;
    }

    /**
     * Same contract as {@link #nullableValidatedDouble}, additionally requiring the value be either
     * exactly {@code -1.0}(「入手不可」の特別値)or within {@code [0.0, 1.0]}. Anything else (e.g.
     * {@code 2.0} or {@code -0.5}) is warned and treated as absent, mirroring the other fail-soft
     * field parsers in this file.
     */
    private static Double nullableValidatedRate(ConfigurationSection section, String key, String scopeName,
            String mobId, String fieldLabel, Logger log, int[] skipped) {
        Double value = nullableValidatedDouble(section, key, scopeName, mobId, fieldLabel, log, skipped);
        if (value == null || value == -1.0 || (value >= 0.0 && value <= 1.0)) {
            return value;
        }
        log.warning("[" + PATH + "] " + scopeName + "." + mobId + " " + fieldLabel
                + " must be -1 or within [0.0, 1.0] (was " + value + "); ignored");
        skipped[0]++;
        return null;
    }

    /**
     * 2026-07-26 H3 レビュー指摘への対応。以前は値を一切検証せず {@link MobStatOverride} を組み立てて
     * いたため、{@code level < 0} や {@code max-health < 0} を書くと {@link #resolve} 呼び出し時に
     * {@link MobProfile} のコンパクトコンストラクタが {@link IllegalArgumentException} を投げ、
     * {@code TrinityForgeSpawnListener} がそれを握りつぶして {@code stamp()} ごとスキップする —
     * つまりそのモブがTF戦闘パイプラインから丸ごと無言で外れる事故につながっていた。ここで
     * 不正な値を検出した時点で該当フィールドだけを未指定(null = 下位層の値のまま)として扱い、
     * {@code parseDrops} と同じく警告ログを出して {@code skipped} に計上する — モブ全体を巻き込まず、
     * その他の正しいフィールドは引き続き適用される。
     *
     * <p>併せて、{@link ConfigurationSection#getDouble(String)} が非数値(パース不能な文字列など)に
     * 対して警告なしで {@code 0.0} を返してしまう問題も避ける: 生の値がNumberでも数値として解釈できる
     * 文字列でもない場合は、ここで検出して警告のうえ無視する({@code toFiniteDouble}/{@code toFiniteInt}
     * を必ず経由する。生の {@code section.getDouble}/{@code getInt} を直接呼ばない)。
     */
    private static StatsResult parseStats(ConfigurationSection stats, String scopeName, String mobId, Logger log) {
        if (stats == null) {
            return new StatsResult(MobStatOverride.EMPTY, 0);
        }
        int[] skipped = {0};
        Integer level = nullableValidatedInt(stats, "level", scopeName, mobId, "stats.level", log, skipped);
        if (level != null && level < 0) {
            log.warning("[" + PATH + "] " + scopeName + "." + mobId + " stats.level must be >= 0 (was "
                    + level + "); ignored");
            skipped[0]++;
            level = null;
        }
        Double maxHealth = nullableValidatedDouble(stats, "max-health", scopeName, mobId, "stats.max-health",
                log, skipped);
        if (maxHealth != null && maxHealth < 0) {
            log.warning("[" + PATH + "] " + scopeName + "." + mobId + " stats.max-health must be >= 0 (was "
                    + maxHealth + "); ignored");
            skipped[0]++;
            maxHealth = null;
        }
        // 2026-08-14 倍率キー。難易度を「そのレベルで本来決まる強さの N 倍」として表現するためのもの
        // (絶対値だと level: dynamic のダンジョンと両立しない。MobStatOverride の javadoc 参照)。
        Double maxHealthMultiplier = nullablePositiveMultiplier(stats, "max-health-multiplier", scopeName,
                mobId, "stats.max-health-multiplier", log, skipped);
        Double attackPowerMultiplier = nullablePositiveMultiplier(stats, "attack-power-multiplier", scopeName,
                mobId, "stats.attack-power-multiplier", log, skipped);
        Double armorStrength = nullableValidatedDouble(stats, "armor-strength", scopeName, mobId,
                "stats.armor-strength", log, skipped);
        MobStatOverride.DefenseFieldOverride physical =
                parseDefense(stats.getConfigurationSection("physical"), scopeName, mobId, "physical", log, skipped);
        MobStatOverride.DefenseFieldOverride magical =
                parseDefense(stats.getConfigurationSection("magical"), scopeName, mobId, "magical", log, skipped);
        MobStatOverride.AttackFieldOverride attack =
                parseAttack(stats.getConfigurationSection("attack"), scopeName, mobId, log, skipped);
        MobStatOverride result = new MobStatOverride(level, maxHealth, maxHealthMultiplier, armorStrength,
                attackPowerMultiplier, physical, magical, attack);
        return new StatsResult(result, skipped[0]);
    }

    /**
     * 倍率キー(2026-08-14)のパーサ。{@link #nullableValidatedDouble} の契約(未指定は静かに {@code null}、
     * 非数値/非有限は警告して無視)に加えて<b>「0 より大きい」ことを要求</b>する。
     *
     * <p>0 と負値を通さない理由は「掛け算として無意味だから」ではなく<b>実害が真逆だから</b>:
     * {@code max-health} が 0 は「未設定 = EliteMobs 自身の HP を使う」、{@code attack-power} が 0 は
     * {@code MobProfile#hasAttack()} が false = 「TF の攻撃側を使わない」を意味する。つまり
     * {@code max-health-multiplier: 0} と書いた人は「HP を 0 にする」つもりでも、実際には
     * <b>そのモブの HP 設定ごと消えて EliteMobs 既定の HP に戻る</b>。負値に至っては
     * {@link MobProfile} のコンパクトコンストラクタが例外を投げ、スポーンリスナーがそれを握り潰して
     * モブが TF 戦闘パイプラインから丸ごと外れる(2026-07-26 H3 と同じ経路)。どちらも「無言で効かない」
     * ではなく「無言で別のことが起きる」ので、ここで警告して捨てる。
     *
     * <p><b>クォートされた数値文字列({@code "2.5"})も受け付けない</b>(2026-08-14 に方針変更)。
     * 他の数値キーは {@code toFiniteDouble} が文字列もパースするが、倍率キーだけは
     * <b>config-editor と受理範囲を揃える</b>ことを優先した: editor 側のバリデータ
     * ({@code tools/config-editor/lib/schema.js} の {@code isNumber} = {@code typeof value === "number"})
     * は文字列を弾くので、Java だけが受け付けると「手書きで {@code "2.5"} と書いた yml を editor で開くと
     * <b>ファイルごと保存できなくなる</b>」という非対称が生まれる。狭い側へ寄せても既存設定は壊れない
     * ——2026-08-14 実測で出荷 {@code combat/mob-overrides.yml} の倍率キーは 40 件(scope 直下 18 /
     * per-mob 22)あるが、<b>全件が素の数値でクォート文字列は 0 件</b>。件数は増えていくので、
     * この判定を広げ直すときは実データを数え直すこと。
     */
    private static Double nullablePositiveMultiplier(ConfigurationSection section, String key, String scopeName,
            String mobId, String fieldLabel, Logger log, int[] skipped) {
        if (section.contains(key) && !(section.get(key) instanceof Number)) {
            log.warning("[" + PATH + "] " + scopeName + "." + mobId + " " + fieldLabel
                    + " must be numeric and unquoted (was '" + section.get(key) + "'); ignored");
            skipped[0]++;
            return null;
        }
        Double value = nullableValidatedDouble(section, key, scopeName, mobId, fieldLabel, log, skipped);
        if (value == null || value > 0.0) {
            return value;
        }
        log.warning("[" + PATH + "] " + scopeName + "." + mobId + " " + fieldLabel
                + " must be > 0 (was " + value + "); ignored");
        skipped[0]++;
        return null;
    }

    /**
     * 「正しいキーを間違った階層に書いた」を検出して警告する(2026-08-14)。倍率キーは
     * {@code stats:} 直下だが、対になる絶対値 {@code attack-power} は {@code stats.attack:} の中に
     * あるため、{@code attack:} の中へ書いてしまうのは十分あり得る書き間違い。Bukkit の
     * {@link ConfigurationSection} は未知キーを黙って捨てるので、放置すると
     * <b>「書いたのに何も起きない」が警告なしで成立する</b> —— このリポジトリで繰り返し事故になっている
     * パターンなので、明示的に潰しておく。
     */
    private static void warnMisplacedKey(ConfigurationSection section, String key, String correctPath,
            String scopeName, String mobId, String wrongPath, Logger log, int[] skipped) {
        if (section.contains(key)) {
            log.warning("[" + PATH + "] " + scopeName + "." + mobId + " " + wrongPath
                    + " is not a valid key; write it as " + correctPath + " instead; ignored");
            skipped[0]++;
        }
    }

    private static MobStatOverride.DefenseFieldOverride parseDefense(ConfigurationSection section,
            String scopeName, String mobId, String fieldPrefix, Logger log, int[] skipped) {
        if (section == null) {
            return null;
        }
        return new MobStatOverride.DefenseFieldOverride(
                nullableValidatedDouble(section, "defense-rate", scopeName, mobId,
                        "stats." + fieldPrefix + ".defense-rate", log, skipped),
                nullableValidatedDouble(section, "resistance", scopeName, mobId,
                        "stats." + fieldPrefix + ".resistance", log, skipped),
                nullableValidatedDouble(section, "damage-reduction", scopeName, mobId,
                        "stats." + fieldPrefix + ".damage-reduction", log, skipped),
                nullableValidatedDouble(section, "flat-defense", scopeName, mobId,
                        "stats." + fieldPrefix + ".flat-defense", log, skipped));
    }

    private static MobStatOverride.AttackFieldOverride parseAttack(ConfigurationSection section,
            String scopeName, String mobId, Logger log, int[] skipped) {
        if (section == null) {
            return null;
        }
        // 2026-08-14: 倍率キー 2 本はどちらも stats: 直下。attack-power-multiplier は対になる
        // attack-power がこの attack: の中にあるので混同しやすく、ここに書くと黙って捨てられる
        // (warnMisplacedKey 参照)。max-health-multiplier にも同じ検査を張るのは、難易度が
        // 「HP 何倍・攻撃力何倍」の対で書かれるものだから ——【対のうち片方しか警告しないと、
        // 警告に従って attack-power-multiplier だけ直したのに max-health-multiplier は
        // attack: の中に残ったまま無言で不発、という一番たちの悪い直り方をする】。
        warnMisplacedKey(section, "attack-power-multiplier", "stats.attack-power-multiplier", scopeName, mobId,
                "stats.attack.attack-power-multiplier", log, skipped);
        warnMisplacedKey(section, "max-health-multiplier", "stats.max-health-multiplier", scopeName, mobId,
                "stats.attack.max-health-multiplier", log, skipped);
        return new MobStatOverride.AttackFieldOverride(
                // "attack-power" (not "default-damage"): matches combat/mob-profiles.yml's/
                // combat/mob-types.yml's own attack: key vocabulary for this same AttackStats.defaultDamage
                // field (2026-07-26 spec要件「mob-profiles.ymlと同じキー体系にすること」).
                nullableValidatedDouble(section, "attack-power", scopeName, mobId, "stats.attack.attack-power",
                        log, skipped),
                nullableValidatedDouble(section, "flat-bonus-damage", scopeName, mobId,
                        "stats.attack.flat-bonus-damage", log, skipped),
                nullableValidatedDouble(section, "percent-bonus-damage", scopeName, mobId,
                        "stats.attack.percent-bonus-damage", log, skipped),
                nullableValidatedDouble(section, "crit-chance", scopeName, mobId, "stats.attack.crit-chance",
                        log, skipped),
                nullableValidatedDouble(section, "crit-damage", scopeName, mobId, "stats.attack.crit-damage",
                        log, skipped),
                nullableValidatedDouble(section, "penetration", scopeName, mobId, "stats.attack.penetration",
                        log, skipped),
                nullableValidatedDouble(section, "damage-modifier", scopeName, mobId,
                        "stats.attack.damage-modifier", log, skipped),
                nullableValidatedDouble(section, "fixed-damage", scopeName, mobId, "stats.attack.fixed-damage",
                        log, skipped),
                // 2026-08-02: このモブの通常攻撃を魔法として解決する割合[0,1]。attack-power等の他フィールド
                // を1件も書かなくても単独で設定できる(MobStatOverride.AttackFieldOverride javadoc参照)ので、
                // EliteMobsダンジョンモブ(mob-profiles.ymlにattack:が無くEliteMobs自身の式のまま)にも
                // 「魔法として解決する」ことだけを乗せられる。[0,1]範囲外は警告のうえ無視。
                nullableValidatedRate(section, "magic-ratio", scopeName, mobId, "stats.attack.magic-ratio",
                        log, skipped));
    }

    /**
     * {@code null} when the key is absent (silent — normal "not overridden" case). When present but the
     * raw value is neither a {@link Number} nor a numeric string, warns and returns {@code null} instead
     * of silently falling back to {@code 0.0} the way {@link ConfigurationSection#getDouble(String)}
     * does on its own.
     */
    private static Double nullableValidatedDouble(ConfigurationSection section, String key, String scopeName,
            String mobId, String fieldLabel, Logger log, int[] skipped) {
        if (!section.contains(key)) {
            return null;
        }
        Object raw = section.get(key);
        Double value = toFiniteDouble(raw);
        if (value == null) {
            log.warning("[" + PATH + "] " + scopeName + "." + mobId + " " + fieldLabel
                    + " must be numeric (was '" + raw + "'); ignored");
            skipped[0]++;
        }
        return value;
    }

    /** Same contract as {@link #nullableValidatedDouble}, integer-valued. */
    private static Integer nullableValidatedInt(ConfigurationSection section, String key, String scopeName,
            String mobId, String fieldLabel, Logger log, int[] skipped) {
        if (!section.contains(key)) {
            return null;
        }
        Object raw = section.get(key);
        Integer value = toFiniteInt(raw);
        if (value == null) {
            log.warning("[" + PATH + "] " + scopeName + "." + mobId + " " + fieldLabel
                    + " must be an integer (was '" + raw + "'); ignored");
            skipped[0]++;
        }
        return value;
    }

    private static Double toFiniteDouble(Object raw) {
        if (raw instanceof Number number) {
            double value = number.doubleValue();
            return Double.isFinite(value) ? value : null;
        }
        if (raw instanceof String str) {
            try {
                double value = Double.parseDouble(str.trim());
                return Double.isFinite(value) ? value : null;
            } catch (NumberFormatException ex) {
                return null;
            }
        }
        return null;
    }

    private static Integer toFiniteInt(Object raw) {
        if (raw instanceof Number number) {
            return number.intValue();
        }
        if (raw instanceof String str) {
            try {
                return Integer.parseInt(str.trim());
            } catch (NumberFormatException ex) {
                return null;
            }
        }
        return null;
    }

    private static DropsResult parseDrops(List<?> raw, String scopeName, String mobId, Logger log) {
        java.util.List<MobOverrideDropEntry> drops = new java.util.ArrayList<>();
        int skipped = 0;
        if (raw == null) {
            return new DropsResult(drops, 0);
        }
        for (Object item : raw) {
            if (!(item instanceof Map<?, ?> map)) {
                log.warning("[" + PATH + "] " + scopeName + "." + mobId + " drops has a non-mapping entry; skipped");
                skipped++;
                continue;
            }
            Object itemRaw = map.get("item");
            if (itemRaw == null) {
                log.warning("[" + PATH + "] " + scopeName + "." + mobId + " drops entry missing 'item'; skipped");
                skipped++;
                continue;
            }
            String token = String.valueOf(itemRaw).trim();
            Material material = null;
            String catalogId = null;
            if (token.regionMatches(true, 0, CUSTOM_PREFIX, 0, CUSTOM_PREFIX.length())) {
                catalogId = token.substring(CUSTOM_PREFIX.length()).trim();
                if (catalogId.isEmpty()) {
                    log.warning("[" + PATH + "] " + scopeName + "." + mobId
                            + " drops 'custom:' id must not be blank; skipped");
                    skipped++;
                    continue;
                }
            } else {
                try {
                    material = Material.valueOf(token.toUpperCase(Locale.ROOT));
                } catch (IllegalArgumentException ex) {
                    log.warning("[" + PATH + "] " + scopeName + "." + mobId + " drops item '" + token
                            + "' invalid; skipped");
                    skipped++;
                    continue;
                }
            }
            try {
                double chance = clamp01(requireDouble(map, "chance"));
                int min = requireInt(map, "min");
                int max = requireInt(map, "max");
                drops.add(catalogId != null
                        ? MobOverrideDropEntry.ofCatalog(catalogId, chance, min, max)
                        : MobOverrideDropEntry.ofMaterial(material, chance, min, max));
            } catch (IllegalArgumentException ex) {
                log.warning("[" + PATH + "] " + scopeName + "." + mobId + " drops for " + token + " invalid ("
                        + ex.getMessage() + "); skipped");
                skipped++;
            }
        }
        return new DropsResult(drops, skipped);
    }

    private static double requireDouble(Map<?, ?> raw, String field) {
        Object value = raw.get(field);
        if (!(value instanceof Number number)) {
            throw new IllegalArgumentException("'" + field + "' is required and must be numeric");
        }
        return number.doubleValue();
    }

    private static int requireInt(Map<?, ?> raw, String field) {
        Object value = raw.get(field);
        if (!(value instanceof Number number)) {
            throw new IllegalArgumentException("'" + field + "' is required and must be numeric");
        }
        return number.intValue();
    }

    private static double clamp01(double value) {
        return Math.max(0.0, Math.min(1.0, value));
    }

    /** Parse outcome: the immutable scope map and how many mob entries/drops were skipped. */
    record ParseResult(Map<String, Map<String, MobOverrideEntry>> scopes,
                       Map<String, String> scopeDisplayNames,
                       Map<String, MobStatOverride> scopeStats,
                       int skipped, int mobCount) {

        /** Back-compat for tests written before ダンジョン表示名 (2026-07-26) existed. */
        ParseResult(Map<String, Map<String, MobOverrideEntry>> scopes, int skipped, int mobCount) {
            this(scopes, Map.of(), Map.of(), skipped, mobCount);
        }

        /** Back-compat for callers written before scope直下の {@code stats:} (2026-08-03) existed. */
        ParseResult(Map<String, Map<String, MobOverrideEntry>> scopes, Map<String, String> scopeDisplayNames,
                    int skipped, int mobCount) {
            this(scopes, scopeDisplayNames, Map.of(), skipped, mobCount);
        }
    }

    private record DropsResult(List<MobOverrideDropEntry> drops, int skipped) {
    }

    /** Parse outcome for one mob's {@code stats:} block: the merged override plus how many of its
     *  individual fields were invalid and dropped (2026-07-26 H3). */
    private record StatsResult(MobStatOverride stats, int skipped) {
    }
}
